sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t JouniJokelainenRiveria/reacapp -f Dockerfile.dev .
script:
  - docker run -e CI=true JouniJokelainenRiveria/reacapp npm run test